language: julia
os:
# - linux
  - osx
julia:
#  - "0.7"
  - "1.0"
#  - nightly
notifications:
  email: false
#script: # the default script is equivalent to the following
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("PlanetarySystem"); Pkg.test("Example2018"; coverage=true)';
after_success:
  - julia --compilecache=no -e 'cd(Pkg.dir("PlanetarySystem")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
#  - julia -e 'cd(Pkg.dir("PlanetarySystem")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';

